#include "tester.h"

t_lex	g_lexer = lexer;

int		main()
{
	tester("hello|||>>haha|&&", "WORD@hello#||#|#>>#WORD@haha#|#&&");
	tester("hello=wejfh=", "=@hello=wejfh=");
	tester("$hellowejfh", "$@$hellowejfh");
	tester("$hellowejfh", "$@$hellowejfh");
	tester("echo bonjour ; | . 2", "WORD@echo#WORD@bonjour#;#|#WORD@.#WORD@2");
	tester("echo bonjour | | . 2", "WORD@echo#WORD@bonjour#|#|#WORD@.#WORD@2");
	tester("echo bonjour ; ls . bonjour ; ls", "WORD@echo#WORD@bonjour#;#WORD@ls#WORD@.#WORD@bonjour#;#WORD@ls");
	tester("cd $HOME/Bureau .", "WORD@cd#$@$HOME/Bureau#WORD@.");
	tester("cat /dev/random | head -n 1 | cat -e .", "WORD@cat#WORD@/dev/random#|#WORD@head#WORD@-n#WORD@1#|#WORD@cat#WORD@-e#WORD@.");
	tester("cat Makefile | grep pr | head -n 5 | cd test (mybin) . 1", "WORD@cat#WORD@Makefile#|#WORD@grep#WORD@pr#|#WORD@head#WORD@-n#WORD@5#|#WORD@cd#WORD@test#WORD@(mybin)#WORD@.#WORD@1");
	tester("echo bonjour >>> test .", "WORD@echo#WORD@bonjour#>>#>#WORD@test#WORD@.");
	tester("echo 2 >> out1 > out2 .", "WORD@echo#WORD@2#>>#WORD@out1#>#WORD@out2#WORD@.");
	tester("echo 2 > out1 >> out2 .", "WORD@echo#WORD@2#>#WORD@out1#>>#WORD@out2#WORD@.");
	tester(" cat < test .", "WORD@cat#<#WORD@test#WORD@.");
	tester("cd ../../../../../.. . pwd . /", "WORD@cd#WORD@../../../../../..#WORD@.#WORD@pwd#WORD@.#WORD@/");
	tester("c$var Makefile (avec $var=at) .", "$@c$var#WORD@Makefile#WORD@(avec#=@$var=at)#WORD@.");
	tester("$LESS$VAR .", "$@$LESS$VAR#WORD@.");
	tester("echo bonjour > $test w/ t", "WORD@echo#WORD@bonjour#>#$@$test#WORD@w/#WORD@t");
	tester("echo $PATH", "WORD@echo#$@$PATH");
	tester("echo hi; echo hihi;", "WORD@echo#WORD@hi#;#WORD@echo#WORD@hihi#;");
	tester("echo ;;", "WORD@echo#;#;");
	tester("echo one; echo two; echo three;", "WORD@echo#WORD@one#;#WORD@echo#WORD@two#;#WORD@echo#WORD@three#;#");
	tester("export LOL=lol", "WORD@export#=@LOL=lol");
	tester("export LOL=lala ROR=rara", "WORD@export#=@LOL=lala#=@ROR=rara");
	tester("echo $?", "WORD@echo#$@$?");
	tester("| echo", "|#WORD@echo");
	tester("echo |", "WORD@echo#|");
	tester("echo | | echo", "WORD@echo#|#|#WORD@echo");
	tester("cat < Makefile | grep gcc > output", "WORD@cat#<#WORD@Makefile#|#WORD@grep#WORD@gcc#>#WORD@output");
	tester("cat < nofile | grep gcc > output // $? 1", "WORD@cat#<#WORD@nofile#|#WORD@grep#WORD@gcc#>#WORD@output#WORD@//#$@$?#WORD@1");
	tester("if grep christie /etc/passwd > /dev/null  > then ", "WORD@if#WORD@grep#WORD@christie#WORD@/etc/passwd#>#WORD@/dev/null#>#WORD@then");
	tester("test [-z|-n] $variable", "WORD@test#WORD@[-z#|#WORD@-n]#$@$variable");
	tester("var1=1+1", "=@var1=1+1");
	tester("let $var1", "WORD@let#$@$var1");
	tester("var=$((5*3))", "=@var=$((5*3))");
	tester("=====","WORD@=====");
	tester("=","WORD@=");
	tester("coucou==|& &&>>>","=@coucou==#|#WORD@&#&&#>>#>");
	tester("&&&&&","&&#&&#WORD@&");
	tester("echo $TEST$TEST$TEST","WORD@echo#$@$TEST$TEST$TEST");
	tester("export 1TEST= ;","WORD@export#WORD@1TEST=#;");
	tester("export TEST=LOL ; echo $TEST ;","WORD@export#=@TEST=LOL#;#WORD@echo#$@$TEST#;");
	tester("export TEST=LOL ; echo $TEST$TEST$TEST=lol$TEST","WORD@export#=@TEST=LOL#;#WORD@echo#=@$TEST$TEST$TEST=lol$TEST");
	tester("echo test > ls >> ls >> ls ; echo test >> ls; cat ls","WORD@echo#WORD@test#>#WORD@ls#>>#WORD@ls#>>#WORD@ls#;#WORD@echo#WORD@test#>>#WORD@ls#;#@WORD@cat#WORD@ls");
	tester("hello;haha","WORD@hello#;#WORD@haha");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	tester("","");
	return (EXIT_SUCCESS);
}
